name: random_color_test
description: Test task implementation for Solid Software company

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  audioplayers: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  rive: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.12

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/animations/
